import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 200, lines = 45}
decorations = "Buttonless"
option_as_alt = "Both"
opacity = 1

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 20
